/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-05-27 01:42:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class EmployeeList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1653527314000L));
    _jspx_dependants.put("jar:file:/C:/SpringMVCStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mvc04/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>EmployeeList.jsp</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cp );
      out.write("/css/menuStyle.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cp );
      out.write("/css/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--------------------------------------------------- \r\n");
      out.write("\t#15 EmployeeList.jsp\r\n");
      out.write("\t- 직원 리스트 출력 페이지\r\n");
      out.write("\t- 관리자가 접근하는 직원 데이터 출력 페이지\r\n");
      out.write("\t  (일반 직원이 접근하는 직원 데이터 출력페이지는\r\n");
      out.write("\t   EmpList.jsp로 구성 예정)\r\n");
      out.write(" ---------------------------------------------------->\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<div>\r\n");
      out.write("\t<!-- 메뉴 영역 -->\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"menu\">직원 관리</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"menu\">지역 관리</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"menu\">부서 관리</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"menu\">직위 관리</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"menu\">로그 아웃</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 콘텐츠 영역 -->\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t<h1>[ 직원 관리 ]</h1>\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"직원 추가\" class=\"btn\" onclick=\"\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t<!-- ---------------------------------------------------\t\r\n");
      out.write("\tEMPLOYEEID NAME SSN BIRTHDAY LUNAR LUNARNAME TELEPHONE\r\n");
      out.write("\tDEPARTMENTID DEPARTMENTNAME POSITIONID POSITIONNAME \r\n");
      out.write("\tREGIONID REGIONNAME BASICPAY EXTRAPAY PAY GRADE\r\n");
      out.write("\t----------------------------------------------------  -->\r\n");
      out.write("\t<table id=\"customers\" class=\"table\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<!-- 항목 15EA -->\r\n");
      out.write("\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>주민번호</th>\r\n");
      out.write("\t\t\t<th>생년월일</th>\r\n");
      out.write("\t\t\t<th>양음력</th>\r\n");
      out.write("\t\t\t<th>전화번호</th>\r\n");
      out.write("\t\t\t<th>지역</th>\r\n");
      out.write("\t\t\t<th>부서</th>\r\n");
      out.write("\t\t\t<th>직위</th>\r\n");
      out.write("\t\t\t<th>기본급</th>\r\n");
      out.write("\t\t\t<th>수당</th>\r\n");
      out.write("\t\t\t<th>급여</th>\r\n");
      out.write("\t\t\t<th>등급</th>\r\n");
      out.write("\t\t\t<th>수정</th>\r\n");
      out.write("\t\t\t<th>삭제</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t<td>김상기</td>\r\n");
      out.write("\t\t\t<td>620527</td>\r\n");
      out.write("\t\t\t<td>1962-05-27</td>\r\n");
      out.write("\t\t\t<td>양력</td>\r\n");
      out.write("\t\t\t<td>010-9876-5432</td>\r\n");
      out.write("\t\t\t<td>서울</td>\r\n");
      out.write("\t\t\t<td>개발부</td>\r\n");
      out.write("\t\t\t<td>사원</td>\r\n");
      out.write("\t\t\t<td>1,500,000</td>\r\n");
      out.write("\t\t\t<td>1,500,000</td>\r\n");
      out.write("\t\t\t<td>3,000,000</td>\r\n");
      out.write("\t\t\t<td>관리자</td>\r\n");
      out.write("\t\t\t<td><button type=\"button\" class=\"btn\">수정</button></td>\r\n");
      out.write("\t\t\t<td><button type=\"button\" class=\"btn\">삭제</button></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t<td>이상기</td>\r\n");
      out.write("\t\t\t<td>620527</td>\r\n");
      out.write("\t\t\t<td>1962-05-27</td>\r\n");
      out.write("\t\t\t<td>양력</td>\r\n");
      out.write("\t\t\t<td>010-9876-5432</td>\r\n");
      out.write("\t\t\t<td>서울</td>\r\n");
      out.write("\t\t\t<td>개발부</td>\r\n");
      out.write("\t\t\t<td>사원</td>\r\n");
      out.write("\t\t\t<td>1,500,000</td>\r\n");
      out.write("\t\t\t<td>1,500,000</td>\r\n");
      out.write("\t\t\t<td>3,000,000</td>\r\n");
      out.write("\t\t\t<td>관리자</td>\r\n");
      out.write("\t\t\t<td><button type=\"button\" class=\"btn\">수정</button></td>\r\n");
      out.write("\t\t\t<td><button type=\"button\" class=\"btn\">삭제</button></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t<td>이상기</td>\r\n");
      out.write("\t\t\t<td>620527</td>\r\n");
      out.write("\t\t\t<td>1962-05-27</td>\r\n");
      out.write("\t\t\t<td>양력</td>\r\n");
      out.write("\t\t\t<td>010-9876-5432</td>\r\n");
      out.write("\t\t\t<td>서울</td>\r\n");
      out.write("\t\t\t<td>개발부</td>\r\n");
      out.write("\t\t\t<td>사원</td>\r\n");
      out.write("\t\t\t<td>1,500,000</td>\r\n");
      out.write("\t\t\t<td>1,500,000</td>\r\n");
      out.write("\t\t\t<td>3,000,000</td>\r\n");
      out.write("\t\t\t<td>관리자</td>\r\n");
      out.write("\t\t\t<td><button type=\"button\" class=\"btn\">수정</button></td>\r\n");
      out.write("\t\t\t<td><button type=\"button\" class=\"btn\">삭제</button></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 회사 소개 및 어플리케이션 소개 영역 -->\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
